# admin
ADMIN = "/admin"

ADMIN_DASHBOARD = f"{ADMIN}/dashboard"

# department
DEPARTMENT = "/department"
DEPARTMENT_LIST = f"/{DEPARTMENT}/department-list"
DEPARTMENT_ADD_DEPARTMENT = f"{DEPARTMENT}/add-department"
DEPARTMENT_EDIT_DEPARTMENT = f"{DEPARTMENT}/edit-department"
DEPARTMENT_DELETE_DEPARTMENT = f"{DEPARTMENT}/delete-department"
DEPARTMENT_RESTORE_DEPARTMENT = f"{DEPARTMENT}/restore-department"
DEPARTMENT_EXPORT = f"/{DEPARTMENT}/export"
DEPARTMENT_IMPORT = f"/{DEPARTMENT}/import"
DEPARTMENT_IMPORT_SAMPLE = f"/{DEPARTMENT}/import-sample"

DEPARTMENT_MANAGE_HEADS = f"/{DEPARTMENT}/manage-heads"
DEPARTMENT_ADD_HEAD = f"/{DEPARTMENT}/add-head"
DEPARTMENT_REMOVE_HEAD = f"/{DEPARTMENT}/remove-head"

# doctor
DOCTOR = "/doctor"
DOCTOR_LIST = f"{DOCTOR}/doctor-list"
DOCTOR_ADD_DOCTOR = f"{DOCTOR}/add-doctor"
DOCTOR_EDIT_DOCTOR = f"{DOCTOR}/edit-doctor"
DOCTOR_DELETE_DOCTOR = f"{DOCTOR}/delete-doctor"
DOCTOR_RESTORE_DOCTOR = f"{DOCTOR}/restore-doctor"
DOCTOR_EXPORT = f"{DOCTOR}/export"
DOCTOR_IMPORT = f"{DOCTOR}/import"
DOCTOR_IMPORT_SAMPLE = f"{DOCTOR}/import-sample"

DOCTOR_ASSIGN_DEPARTMENT = f"/{DOCTOR}/assign-department"
DOCTOR_UPDATE_ASSIGN_DEPARTMENT = f"{DOCTOR}/update-assign-department"
DOCTOR_REMOVE_ASSIGN_DEPARTMENT = f"{DOCTOR}/remove-assign-department"
DOCTOR_SHIFT_MANAGEMENT = f"{DOCTOR}/shift-management"
DOCTOR_UPDATE_SHIFT_MANAGEMENT = f"{DOCTOR}/update-shift-management"


# blood-bank
BLOOD_BANK = "/blood-bank"
BLOOD_BANK_DONOR = f"{BLOOD_BANK}/donor"
BLOOD_BANK_ADD_DONOR = f"{BLOOD_BANK}/add-donor"
BLOOD_BANK_EDIT_DONOR = f"{BLOOD_BANK}/edit-donor"
BLOOD_BANK_DELETE_DONOR = f"{BLOOD_BANK}/delete-donor"
BLOOD_BANK_RESTORE_DONOR = f"{BLOOD_BANK}/restore-donor"

BLOOD_BANK_INVENTORY = f'{BLOOD_BANK}/inventory'
BLOOD_BANK_ADD_INVENTORY = f'{BLOOD_BANK}/inventory/add'
BLOOD_BANK_EDIT_INVENTORY = f'{BLOOD_BANK}/inventory/edit'
BLOOD_BANK_DELETE_INVENTORY = f'{BLOOD_BANK}/inventory/delete'
BLOOD_BANK_RESTORE_INVENTORY = f'{BLOOD_BANK}/inventory/restore'

BLOOD_BANK_STOCK = f"{BLOOD_BANK}/stock"
BLOOD_BANK_ADD_STOCK = f"{BLOOD_BANK}/add-stock"
BLOOD_BANK_EDIT_STOCK = f"{BLOOD_BANK}/edit-stock"
BLOOD_BANK_DELETE_STOCK = f"{BLOOD_BANK}/delete-stock"
BLOOD_BANK_RESTORE_STOCK = f"{BLOOD_BANK}/restore-stock"

BLOOD_BANK_ISSUED = f"{BLOOD_BANK}/issued"
BLOOD_BANK_ADD_ISSUED = f"{BLOOD_BANK}/add-issued"
BLOOD_BANK_EDIT_ISSUED = f"{BLOOD_BANK}/edit-issued"
BLOOD_BANK_DELETE_ISSUED = f"{BLOOD_BANK}/delete-issued"
BLOOD_BANK_RESTORE_ISSUED = f"{BLOOD_BANK}/restore-issued"

# Blood Request Routes
BLOOD_BANK_REQUESTS = '/blood-bank/requests'
BLOOD_BANK_ADD_REQUEST = '/blood-bank/requests/add'
BLOOD_BANK_EDIT_REQUEST = '/blood-bank/requests/edit'
BLOOD_BANK_DELETE_REQUEST = '/blood-bank/requests/delete'
BLOOD_BANK_APPROVE_REQUEST = '/blood-bank/requests/approve'
BLOOD_BANK_REJECT_REQUEST = '/blood-bank/requests/reject'
BLOOD_BANK_COMPLETE_REQUEST = '/blood-bank/requests/complete'

# Blood Transfusion Routes
BLOOD_BANK_TRANSFUSIONS = '/blood-bank/transfusions'
BLOOD_BANK_ADD_TRANSFUSION = '/blood-bank/transfusions/add'
BLOOD_BANK_EDIT_TRANSFUSION = '/blood-bank/transfusions/edit'
BLOOD_BANK_DELETE_TRANSFUSION = '/blood-bank/transfusions/delete'

# inventory
# --- Inventory Base Routes ---
INVENTORY_BASE = "/inventory"

# --- Item Categories ---
ITEM_CATEGORIES_BASE = f"{INVENTORY_BASE}/categories"
ITEM_CATEGORIES_LIST = ITEM_CATEGORIES_BASE  # Same as base for list view
ITEM_CATEGORIES_ADD = f"{ITEM_CATEGORIES_BASE}/add"
ITEM_CATEGORIES_EDIT = f"{ITEM_CATEGORIES_BASE}/edit"
ITEM_CATEGORIES_DELETE = f"{ITEM_CATEGORIES_BASE}/delete"
ITEM_CATEGORIES_RESTORE = f"{ITEM_CATEGORIES_BASE}/restore"
ITEM_CATEGORIES_EXPORT = f"{ITEM_CATEGORIES_BASE}/export"
ITEM_CATEGORIES_IMPORT = f"{ITEM_CATEGORIES_BASE}/import"
ITEM_CATEGORIES_IMPORT_SAMPLE = f"{ITEM_CATEGORIES_BASE}/import/sample"

# --- Item Stores ---
ITEM_STORES_BASE = f"{INVENTORY_BASE}/stores"
ITEM_STORES_LIST = ITEM_STORES_BASE # Same as base for list view
ITEM_STORES_ADD = f"{ITEM_STORES_BASE}/add"
ITEM_STORES_EDIT = f"{ITEM_STORES_BASE}/edit" # Expects ID
ITEM_STORES_DELETE = f"{ITEM_STORES_BASE}/delete" # Expects ID
ITEM_STORES_RESTORE = f"{ITEM_STORES_BASE}/restore" # Expects ID
ITEM_STORES_EXPORT = f"{ITEM_STORES_BASE}/export"
ITEM_STORES_IMPORT = f"{ITEM_STORES_BASE}/import"
ITEM_STORES_IMPORT_SAMPLE = f"{ITEM_STORES_BASE}/import/sample"

# --- Item Suppliers ---
ITEM_SUPPLIERS_BASE = f"{INVENTORY_BASE}/suppliers"
ITEM_SUPPLIERS_LIST = ITEM_SUPPLIERS_BASE # Same as base for list view
ITEM_SUPPLIERS_ADD = f"{ITEM_SUPPLIERS_BASE}/add"
ITEM_SUPPLIERS_EDIT = f"{ITEM_SUPPLIERS_BASE}/edit" # Expects ID
ITEM_SUPPLIERS_DELETE = f"{ITEM_SUPPLIERS_BASE}/delete" # Expects ID
ITEM_SUPPLIERS_RESTORE = f"{ITEM_SUPPLIERS_BASE}/restore" # Expects ID
ITEM_SUPPLIERS_EXPORT = f"{ITEM_SUPPLIERS_BASE}/export"
ITEM_SUPPLIERS_IMPORT = f"{ITEM_SUPPLIERS_BASE}/import"
ITEM_SUPPLIERS_IMPORT_SAMPLE = f"{ITEM_SUPPLIERS_BASE}/import/sample"

# --- Inventory Items (Actual Items in Stock) ---
INVENTORY_ITEMS_BASE = f"{INVENTORY_BASE}/items" # Renamed from INVENTORY_ITEMS for consistency
INVENTORY_ITEMS_LIST = INVENTORY_ITEMS_BASE # Renamed from INVENTORY_ITEM_STOCK_LIST for consistency
INVENTORY_ITEMS_ADD = f"{INVENTORY_ITEMS_BASE}/add"
INVENTORY_ITEMS_EDIT = f"{INVENTORY_ITEMS_BASE}/edit" # Expects ID
INVENTORY_ITEMS_DELETE = f"{INVENTORY_ITEMS_BASE}/delete" # Expects ID
INVENTORY_ITEMS_RESTORE = f"{INVENTORY_ITEMS_BASE}/restore" # Expects ID
INVENTORY_ITEMS_EXPORT = f"{INVENTORY_ITEMS_BASE}/export"
INVENTORY_ITEMS_IMPORT = f"{INVENTORY_ITEMS_BASE}/import"
INVENTORY_ITEMS_IMPORT_SAMPLE = f"{INVENTORY_ITEMS_BASE}/import/sample"

# --- Constants for Routes (Matching your provided list) ---
ITEM_STOCKS = f"{INVENTORY_BASE}/item_stocks"
ITEM_STOCKS_ADD = f'{INVENTORY_BASE}/item_stocks/add'
ITEM_STOCKS_EDIT = f'{INVENTORY_BASE}/item_stocks/edit'  # Will append /<int:stock_id>
ITEM_STOCKS_DELETE = f'{INVENTORY_BASE}/item_stocks/delete'  # Will append /<int:stock_id>
ITEM_STOCKS_RESTORE = f'{INVENTORY_BASE}/item_stocks/restore'  # Will append /<int:stock_id>
ITEM_STOCKS_EXPORT = f'{INVENTORY_BASE}/item_stocks/export'  # Will append /<string:file_format>
ITEM_STOCKS_IMPORT = f'{INVENTORY_BASE}/item_stocks/import'
ITEM_STOCKS_IMPORT_SAMPLE = f'{INVENTORY_BASE}/item_stocks/import/sample'
ITEMS_GET_BY_CATEGORY = f'{INVENTORY_BASE}/items/get_by_category'


# --- Issued Items ---
ISSUED_ITEMS_BASE = f"{INVENTORY_BASE}/issued" # Consistent with other bases
ISSUED_ITEMS_LIST = ISSUED_ITEMS_BASE
ISSUED_ITEMS_ADD = f"{ISSUED_ITEMS_BASE}/add"
ISSUED_ITEMS_EDIT = f"{ISSUED_ITEMS_BASE}/edit" # Expects ID
ISSUED_ITEMS_DELETE = f"{ISSUED_ITEMS_BASE}/delete" # Expects ID
ISSUED_ITEMS_RESTORE = f"{ISSUED_ITEMS_BASE}/restore" # Expects ID
ISSUED_ITEMS_RETURN = f"{ISSUED_ITEMS_BASE}/return" # Expects ID
ISSUED_ITEMS_EXPORT = f"{ISSUED_ITEMS_BASE}/export"

# --- Item Requests ---
ITEM_REQUESTS_BASE = f"{INVENTORY_BASE}/requests"
ITEM_REQUESTS_LIST = ITEM_REQUESTS_BASE
ITEM_REQUESTS_APPROVE = f"{ITEM_REQUESTS_BASE}/approve" # Expects ID
ITEM_REQUESTS_REJECT = f"{ITEM_REQUESTS_BASE}/reject" # Expects ID

API_GET_AVAILABLE_STOCK = "/api/item_stock_available" # Used in JS with ADMIN + API_GET_AVAILABLE_STOCK
API_GET_USERS_BY_ROLE = "/api/users_by_role" # Used in JS with ADMIN + API_GET_USERS_BY_ROLE

# accounts
ACCOUNTS = "/accounts"
ACCOUNTS_INCOME = f"{ACCOUNTS}/income"
ACCOUNTS_EXPENSES = f"{ACCOUNTS}/expenses"
ACCOUNTS_INVOICES = f"{ACCOUNTS}/invoices"
ACCOUNTS_PAYMENTS = f"{ACCOUNTS}/payments"
ACCOUNTS_CREATE_INVOICE = f"{ACCOUNTS}/create-invoice"
ACCOUNTS_INVOICES_DETAILS = f"{ACCOUNTS}/invoice-details"

# noticeboard
NOTICEBOARD = "/noticeboard"
NOTICEBOARD_ADD_NOTICE = f"{NOTICEBOARD}/add-notice"
NOTICEBOARD_EDIT_NOTICE = f"{NOTICEBOARD}/edit-notice"
NOTICEBOARD_DELETE_NOTICE = f"{NOTICEBOARD}/delete-notice"
NOTICEBOARD_RESTORE_NOTICE = f"{NOTICEBOARD}/restore-notice"


# ambulance
AMBULANCE_BASE = f"/ambulances"

AMBULANCE_LIST = f"{AMBULANCE_BASE}"
AMBULANCE_ADD = f"{AMBULANCE_BASE}/add"
AMBULANCE_EDIT = f"{AMBULANCE_BASE}/edit"
AMBULANCE_DELETE = f"{AMBULANCE_BASE}/delete"
AMBULANCE_RESTORE = f"{AMBULANCE_BASE}/restore"
AMBULANCE_TOGGLE_STATUS = f"{AMBULANCE_BASE}/toggle-status"
AMBULANCE_EXPORT = f"{AMBULANCE_BASE}/export"
AMBULANCE_IMPORT = f"{AMBULANCE_BASE}/import"
AMBULANCE_IMPORT_SAMPLE = f"{AMBULANCE_BASE}/import/sample"

AMBULANCE_ITEM_BASE = f"{AMBULANCE_BASE}/items"

AMBULANCE_ITEM_LIST = f"{AMBULANCE_ITEM_BASE}"
AMBULANCE_ITEM_ADD = f"{AMBULANCE_ITEM_BASE}/add"
AMBULANCE_ITEM_EDIT = f"{AMBULANCE_ITEM_BASE}/edit"
AMBULANCE_ITEM_DELETE = f"{AMBULANCE_ITEM_BASE}/delete"
AMBULANCE_ITEM_RESTORE = f"{AMBULANCE_ITEM_BASE}/restore"
AMBULANCE_ITEM_TOGGLE_STATUS = f"{AMBULANCE_ITEM_BASE}/toggle-status"
AMBULANCE_ITEM_EXPORT = f"{AMBULANCE_ITEM_BASE}/export"
AMBULANCE_ITEM_IMPORT = f"{AMBULANCE_ITEM_BASE}/import"
AMBULANCE_ITEM_IMPORT_SAMPLE = f"{AMBULANCE_ITEM_BASE}/import/sample"

AJAX_GET_AMBULANCE_ITEM_DETAILS = f"{AMBULANCE_ITEM_BASE}/details"
AJAX_CHECK_AMBULANCE_ITEM_NAME = f"{AMBULANCE_ITEM_BASE}/check-name"

AMBULANCE_CATEGORY_BASE = f"{AMBULANCE_BASE}/categories"

AMBULANCE_CATEGORY_LIST = f"{AMBULANCE_CATEGORY_BASE}"
AMBULANCE_CATEGORY_ADD = f"{AMBULANCE_CATEGORY_BASE}/add"
AMBULANCE_CATEGORY_EDIT = f"{AMBULANCE_CATEGORY_BASE}/edit"
AMBULANCE_CATEGORY_DELETE = f"{AMBULANCE_CATEGORY_BASE}/delete"
AMBULANCE_CATEGORY_RESTORE = f"{AMBULANCE_CATEGORY_BASE}/restore"
AMBULANCE_CATEGORY_TOGGLE_STATUS = f"{AMBULANCE_CATEGORY_BASE}/toggle-status"
AMBULANCE_CATEGORY_EXPORT = f"{AMBULANCE_CATEGORY_BASE}/export"
AMBULANCE_CATEGORY_IMPORT = f"{AMBULANCE_CATEGORY_BASE}/import"
AMBULANCE_CATEGORY_IMPORT_SAMPLE = f"{AMBULANCE_CATEGORY_BASE}/import/sample"

AJAX_GET_AMBULANCE_CATEGORY_DETAILS = f"{AMBULANCE_CATEGORY_BASE}/details"
AJAX_CHECK_AMBULANCE_CATEGORY_NAME = f"{AMBULANCE_CATEGORY_BASE}/check-name"

DRIVER_BASE = f"{AMBULANCE_BASE}/drivers"
AMBULANCE_DRIVER_LIST = f"{DRIVER_BASE}"
AMBULANCE_ADD_DRIVER = f"{DRIVER_BASE}/add"
AMBULANCE_EDIT_DRIVER = f"{DRIVER_BASE}/edit"
AMBULANCE_DELETE_DRIVER = f"{DRIVER_BASE}/delete"
AMBULANCE_RESTORE_DRIVER = f"{DRIVER_BASE}/restore"
AMBULANCE_TOGGLE_STATUS_DRIVER = f"{DRIVER_BASE}/toggle-status"
AMBULANCE_EXPORT_DRIVERS = f"{DRIVER_BASE}/export"
AMBULANCE_IMPORT_DRIVERS = f"{DRIVER_BASE}/import"
AMBULANCE_IMPORT_DRIVERS_SAMPLE = f"{DRIVER_BASE}/import/sample"

AMBULANCE_CALLS_BASE = f"{AMBULANCE_BASE}/calls"

AMBULANCE_AMBULANCE_CALL_LIST = f"{AMBULANCE_CALLS_BASE}"
AMBULANCE_AMBULANCE_ADD_CALL = f"{AMBULANCE_CALLS_BASE}/add"
AMBULANCE_AMBULANCE_EDIT_CALL = f"{AMBULANCE_CALLS_BASE}/edit"
AMBULANCE_AMBULANCE_CALL_VIEW = f"{AMBULANCE_CALLS_BASE}/view"
AMBULANCE_AMBULANCE_DELETE_CALL = f"{AMBULANCE_CALLS_BASE}/delete"
AMBULANCE_AMBULANCE_RESTORE_CALL = f"{AMBULANCE_CALLS_BASE}/restore"
AMBULANCE_AMBULANCE_UPDATE_STATUS_CALL = f"{AMBULANCE_CALLS_BASE}/update-status"
AMBULANCE_AMBULANCE_CALL_LIST_PRINT = f"{AMBULANCE_CALLS_BASE}/print"
AMBULANCE_AMBULANCE_EXPORT_CALLS = f"{AMBULANCE_CALLS_BASE}/export"
AMBULANCE_AMBULANCE_ADD_PAYMENT_TO_CALL = f"{AMBULANCE_CALLS_BASE}/add-payment"


# human-resources
HUMAN_RESOURCES = "/human-resources"
HUMAN_RESOURCES_HR_APPROVALS = f"{HUMAN_RESOURCES}/hr-approvals"
HUMAN_RESOURCES_STAFF_LEAVES = f"{HUMAN_RESOURCES}/staff-leaves"
HUMAN_RESOURCES_STAFF_HOLIDAY = f"{HUMAN_RESOURCES}/staff-holidays"
HUMAN_RESOURCES_STAFF_ATTENDANCE = f"{HUMAN_RESOURCES}/staff-attendance"

# insurance
INSURANCE = "/insurance"
INSURANCE_CONVERAGE_TYPE = f"/{INSURANCE}/coverage-types"
INSURANCE_ADD_CONVERAGE_TYPE = f"{INSURANCE}/add-coverage-type"
INSURANCE_EDIT_CONVERAGE_TYPE = f"{INSURANCE}/edit-coverage-type"
INSURANCE_DELETE_CONVERAGE_TYPE = f"{INSURANCE}/delete-coverage-type"
INSURANCE_RESTORE_CONVERAGE_TYPE = f"{INSURANCE}/restore-coverage-type"

INSURANCE_PATIENT = f"{INSURANCE}/patient"
INSURANCE_PATIENT_ADD_RECORDS = f"{INSURANCE_PATIENT}/add-records"
INSURANCE_PATIENT_EDIT_RECORDS = f"{INSURANCE_PATIENT}/edit-records"
INSURANCE_PATIENT_DELETE_RECORDS = f"{INSURANCE_PATIENT}/delete-records"
INSURANCE_PATIENT_RESTORE_RECORDS = f"{INSURANCE_PATIENT}/restore-records"

INSURANCE_PROVIDER = f"/{INSURANCE}/provider"
INSURANCE_ADD_INSURANCE_PROVIDER = f"{INSURANCE}/add-insurance-provider"
INSURANCE_EDIT_INSURANCE_PROVIDER = f"{INSURANCE}/edit-insurance-provider"
INSURANCE_DELETE_INSURANCE_PROVIDER = f"{INSURANCE}/delete-insurance-provider"
INSURANCE_RESTORE_INSURANCE_PROVIDER = f"{INSURANCE}/restore-insurance-provider"

INSURANCE_CLAIM_STATUS = f"{INSURANCE}/claim-status"
INSURANCE_NEW_CLAIM = f"{INSURANCE}/new-claim"
INSURANCE_CLAIM_STATUS_EDIT = f"{INSURANCE}/edit-claim-status"
INSURANCE_CLAIM_STATUS_DELETE = f"{INSURANCE}/delete-claim-status"
INSURANCE_CLAIM_STATUS_RESTORE = f"{INSURANCE}/restore-claim-status"

INSURANCE_CLAIM_STATUS_PROCESS = f"{INSURANCE}/claim-status-process"
INSURANCE_CLAIM_STATUS_APPEAL = f"{INSURANCE}/claim-status-appeal"
INSURANCE_CLAIM_STATUS_PRINT = f"{INSURANCE}/claim-status-print"



# Base Pharmacy URL
PHARMACY = "/pharmacy"

# --- Dashboard ---
PHARMACY_DASHBOARD = f"{PHARMACY}/dashboard"

# --- Sales & Billing ---
PHARMACY_SALES = f"{PHARMACY}/sales"
PHARMACY_SALES_LIST = PHARMACY_SALES  # Main sales list
PHARMACY_SALES_ADD = f"{PHARMACY_SALES}/new"
PHARMACY_SALES_VIEW = f"{PHARMACY_SALES}/view"  # Use /view/<id> in actual route
PHARMACY_SALES_EDIT = f"{PHARMACY_SALES}/edit"  # Use /edit/<id> in actual route
PHARMACY_SALES_DELETE = f"{PHARMACY_SALES}/delete" # Use /delete/<id> in actual route
PHARMACY_SALES_RESTORE = f"{PHARMACY_SALES}/restore" # Use /restore/<id> in actual route
PHARMACY_SALES_PRINT = f"{PHARMACY_SALES}/print" # Use /print/<id> in actual route
PHARMACY_SALES_EXPORT = f"{PHARMACY_SALES}/export" # Export all sales

PHARMACY_SALES_RETURNS = f"{PHARMACY_SALES}/returns" # Main sales returns page
PHARMACY_SALES_RETURN_ITEM = f"{PHARMACY_SALES}/return-item" # Use /return-item/<id> for specific item

# --- Inventory & Stock ---
PHARMACY_INVENTORY = f"{PHARMACY}/inventory"

# Medicines
PHARMACY_MEDICINES = f"{PHARMACY_INVENTORY}/medicines"
PHARMACY_MEDICINES_LIST = PHARMACY_MEDICINES # All Medicines
PHARMACY_MEDICINE_ADD = f"{PHARMACY_MEDICINES}/add"
PHARMACY_MEDICINE_VIEW = f"{PHARMACY_MEDICINES}/view" # Use /view/<id> in actual route
PHARMACY_MEDICINE_EDIT = f"{PHARMACY_MEDICINES}/edit" # Use /edit/<id> in actual route
PHARMACY_MEDICINE_DELETE = f"{PHARMACY_MEDICINES}/delete" # Use /delete/<id> in actual route
PHARMACY_MEDICINE_RESTORE = f"{PHARMACY_MEDICINES}/restore" # Use /restore/<id> in actual route
PHARMACY_MEDICINE_EXPORT = f"{PHARMACY_MEDICINES}/export"
PHARMACY_MEDICINE_IMPORT = f"{PHARMACY_MEDICINES}/import"
PHARMACY_MEDICINE_IMPORT_SAMPLE = f"{PHARMACY_MEDICINES}/import-sample"
PHARMACY_MEDICINE_DISPENSE = f"{PHARMACY_MEDICINES}/dispense" # Renamed from _DISPENSE
PHARMACY_MEDICINE_RESTOCK = f"{PHARMACY_MEDICINES}/restock" # Renamed from _RESTOCK

# Stock Levels
PHARMACY_STOCK_LEVELS = f"{PHARMACY_INVENTORY}/stock-levels"

# Medicine Batches
PHARMACY_MEDICINE_BATCHES = f"{PHARMACY_INVENTORY}/batches"
PHARMACY_MEDICINE_BATCHES_LIST = PHARMACY_MEDICINE_BATCHES
PHARMACY_MEDICINE_BATCHES_ADD = f"{PHARMACY_MEDICINE_BATCHES}/add"
PHARMACY_MEDICINE_BATCHES_EDIT = f"{PHARMACY_MEDICINE_BATCHES}/edit" # Use /edit/<id> in actual route
PHARMACY_MEDICINE_BATCHES_DELETE = f"{PHARMACY_MEDICINE_BATCHES}/delete" # Use /delete/<id> in actual route

# Purchases
PHARMACY_PURCHASES = f"{PHARMACY_INVENTORY}/purchases"
PHARMACY_PURCHASES_LIST = PHARMACY_PURCHASES # Purchases list
PHARMACY_PURCHASES_ADD = f"{PHARMACY_PURCHASES}/add"
PHARMACY_PURCHASES_VIEW = f"{PHARMACY_PURCHASES}/view" # Use /view/<id> in actual route
PHARMACY_PURCHASES_EDIT = f"{PHARMACY_PURCHASES}/edit" # Use /edit/<id> in actual route
PHARMACY_PURCHASES_DELETE = f"{PHARMACY_PURCHASES}/delete" # Use /delete/<id> in actual route
PHARMACY_PURCHASES_RESTORE = f"{PHARMACY_PURCHASES}/restore" # Use /restore/<id> in actual route
PHARMACY_PURCHASES_PRINT = f"{PHARMACY_PURCHASES}/print" # Use /print/<id> in actual route
PHARMACY_PURCHASES_PAYMENT = f"{PHARMACY_PURCHASES}/payment" # Use /payment/<id> in actual route
PHARMACY_PURCHASES_RETURN = f"{PHARMACY_PURCHASES}/return" # Use /return/<id> for full purchase return
PHARMACY_PURCHASES_EXPORT = f"{PHARMACY_PURCHASES}/export"

# Stock Adjustments
PHARMACY_STOCK_ADJUSTMENTS = f"{PHARMACY_INVENTORY}/adjustments"
PHARMACY_STOCK_ADJUSTMENTS_LIST = PHARMACY_STOCK_ADJUSTMENTS
PHARMACY_STOCK_ADJUSTMENTS_ADD = f"{PHARMACY_STOCK_ADJUSTMENTS}/add"
PHARMACY_STOCK_ADJUSTMENTS_VIEW = f"{PHARMACY_STOCK_ADJUSTMENTS}/view" # Use /view/<id> in actual route

# Stock Transactions (Read-only historical log)
PHARMACY_STOCK_TRANSACTIONS = f"{PHARMACY_INVENTORY}/transactions"

# --- Master Data ---
PHARMACY_MASTER_DATA = f"{PHARMACY}/master-data"

# Categories
PHARMACY_CATEGORIES = f"{PHARMACY_MASTER_DATA}/categories"
PHARMACY_CATEGORIES_LIST = PHARMACY_CATEGORIES
PHARMACY_CATEGORIES_ADD = f"{PHARMACY_CATEGORIES}/add"
PHARMACY_CATEGORIES_EDIT = f"{PHARMACY_CATEGORIES}/edit" # Use /edit/<id> in actual route
PHARMACY_CATEGORIES_DELETE = f"{PHARMACY_CATEGORIES}/delete" # Use /delete/<id> in actual route
PHARMACY_CATEGORIES_RESTORE = f"{PHARMACY_CATEGORIES}/restore" # Use /restore/<id> in actual route
PHARMACY_CATEGORIES_EXPORT = f"{PHARMACY_CATEGORIES}/export"
PHARMACY_CATEGORIES_IMPORT = f"{PHARMACY_CATEGORIES}/import"
PHARMACY_CATEGORIES_IMPORT_SAMPLE = f"{PHARMACY_CATEGORIES}/import-sample"

# Companies
PHARMACY_COMPANIES = f"{PHARMACY_MASTER_DATA}/companies"
PHARMACY_COMPANIES_LIST = PHARMACY_COMPANIES
PHARMACY_COMPANIES_ADD = f"{PHARMACY_COMPANIES}/add"
PHARMACY_COMPANIES_EDIT = f"{PHARMACY_COMPANIES}/edit" # Use /edit/<id> in actual route
PHARMACY_COMPANIES_DELETE = f"{PHARMACY_COMPANIES}/delete" # Use /delete/<id> in actual route
PHARMACY_COMPANIES_RESTORE = f"{PHARMACY_COMPANIES}/restore" # Use /restore/<id> in actual route
PHARMACY_COMPANIES_EXPORT = f"{PHARMACY_COMPANIES}/export"
PHARMACY_COMPANIES_IMPORT = f"{PHARMACY_COMPANIES}/import"
PHARMACY_COMPANIES_IMPORT_SAMPLE = f"{PHARMACY_COMPANIES}/import-sample"

# Suppliers
PHARMACY_SUPPLIERS = f"{PHARMACY_MASTER_DATA}/suppliers"
PHARMACY_SUPPLIERS_LIST = PHARMACY_SUPPLIERS
PHARMACY_SUPPLIERS_ADD = f"{PHARMACY_SUPPLIERS}/add"
PHARMACY_SUPPLIERS_EDIT = f"{PHARMACY_SUPPLIERS}/edit" # Use /edit/<id> in actual route
PHARMACY_SUPPLIERS_DELETE = f"{PHARMACY_SUPPLIERS}/delete" # Use /delete/<id> in actual route
PHARMACY_SUPPLIERS_RESTORE = f"{PHARMACY_SUPPLIERS}/restore" # Use /restore/<id> in actual route
PHARMACY_SUPPLIERS_EXPORT = f"{PHARMACY_SUPPLIERS}/export"
PHARMACY_SUPPLIERS_IMPORT = f"{PHARMACY_SUPPLIERS}/import"
PHARMACY_SUPPLIERS_IMPORT_SAMPLE = f"{PHARMACY_SUPPLIERS}/import-sample"

# --- Reports ---
PHARMACY_REPORTS = f"{PHARMACY}/reports"
PHARMACY_REPORTS_SALES_SUMMARY = f"{PHARMACY_REPORTS}/sales-summary"
PHARMACY_REPORTS_STOCK_MOVEMENT = f"{PHARMACY_REPORTS}/stock-movement"
PHARMACY_REPORTS_PURCHASE_HISTORY = f"{PHARMACY_REPORTS}/purchase-history"

# records
RECORDS = "/records"
RECORDS_DEATH = f"/{RECORDS}/death"
RECORDS_ADD_DEATH = f"{RECORDS}/add-death"
RECORDS_DEATH_DELETE = f"{RECORDS}/death-delete"
RECORDS_DEATH_EDIT = f"{RECORDS}/death-edit"
RECORDS_RESTORE_DEATH = f"{RECORDS}/death-restore"
RECORDS_DEATH_CERTIFICATE = f"{RECORDS}/death-certificate"

RECORDS_BIRTH = f"/{RECORDS}/birth"
RECORDS_BIRTH_CERTIFICATE = f"{RECORDS}/birth-certificate"
RECORDS_ADD_BIRTH = f"{RECORDS}/add-birth"
RECORDS_BIRTH_DELETE = f"{RECORDS}/birth-delete"
RECORDS_BIRTH_EDIT = f"{RECORDS}/birth-edit"
RESTORE_RECORDS_BIRTH = f"{RECORDS}/restore-birth"

RECORDS_BIRTH_MEDICAL_VISIT = f"{RECORDS}/birth-visit"
RECORDS_BIRTH_ADD_MEDICAL_VISIT = f"{RECORDS}/add-birth-visit"
RECORDS_BIRTH_EDIT_MEDICAL_VISIT = f"{RECORDS}/birth-edit-visit"
RECORDS_BIRTH_MEDICAL_VISIT_DELETE = f"{RECORDS}/birth-visit-delete"
RESTORE_BIRTH_MEDICAL_VISIT = f"{RECORDS}/restore-birth-visit"

# room
ROOM = "/room"
ROOM_ADD_ROOM = f"/{ROOM}/add-room"
ROOM_ADD_BAD = f"/{ROOM}/add-bad"
ROOM_DELETE_BAD = f"{ROOM}/delete-bad"
ROOM_EDIT_ROOM = f"{ROOM}/edit-room"
ROOM_DELETE_ROOM = f"{ROOM}/delete-room"
ROOM_RESTORE_ROOM = f"{ROOM}/restore-room"
ROOM_IMPORT = f"{ROOM}/import"
ROOM_EXPORT = f"{ROOM}/export"
ROOM_DISCHARGE_ROOM = f"{ROOM}/discharge-room"
ROOM_CLEANING_LOGS = f"{ROOM}/cleaning-logs"
ROOM_COMPLETE_CLEANING_LOGS = f"{ROOM}/complete-cleaning-logs"
ROOM_AVAILABLE_ROOM = f"{ROOM}/available-room"
ROOM_BOOK_ROOM = f"{ROOM}/book-room"
ROOM_ROOM_STATISTICS = f"{ROOM}/room-statistics"
ROOM_ROOM_ALLOTTED = f"/{ROOM}/rooms-allotted"
ROOM_ROOM_BY_DEPT = f"{ROOM}/rooms-by-dept"

GET_PATIENT = "/get-patient"
GET_ROOM_DEPARTMENT = "/get-room-department"

STAFF = "/staff"
STAFF_ADD = f"{STAFF}/add-staff"
STAFF_EDIT = f"{STAFF}/edit-staff"
STAFF_DELETE = f"{STAFF}/delete-staff"
STAFF_RESTORE = f"{STAFF}/restore-staff"


# treatments
TREATMENTS = "/treatments"
TREATMENTS_ADD = f"{TREATMENTS}/add-treatments"
TREATMENTS_EDIT = f"{TREATMENTS}/edit-treatments"
TREATMENTS_TOGGLE_STATUS = f"{TREATMENTS}/toggle-status"
TREATMENTS_DELETE = f"{TREATMENTS}/delete-treatments"
TREATMENTS_RESTORE = f"{TREATMENTS}/restore-treatments"
